=== FatSharky/Task3/src/source/MenuSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/MenuSchema"
	xmlns:tns="http://www.example.org/MenuSchema" elementFormDefault="qualified">


	<element name="menu">
		<complexType>
			<sequence>
				<element name="kind" type="tns:Kind" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Kind">
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="kind-name" type="string" />
			<element name="kind-content" type="tns:KindContent" />
		</sequence>
		<attribute name="id" type="ID" use="required" />
	</complexType>

	<complexType name="KindContent">
		<sequence>
			<element name="dish" type="tns:Dish" minOccurs="0" maxOccurs="unbounded" />
		</sequence>

	</complexType>

	<complexType name="Dish">
		<sequence>
			<element name="photo" type="string" />
			<element name="name" type="tns:Name" />
			<element name="description" type="tns:Description" />
			<element name="portion" type="tns:Portion" />
			<element name="price" type="tns:Price" />
		</sequence>
		<attribute name="id" type="ID" use="required" />
	</complexType>
	<simpleType name="Name">
		<restriction base="string">
			<minLength value="1"></minLength>
			<maxLength value="20"></maxLength>
		</restriction>
	</simpleType>
	<simpleType name="Description">
		<restriction base="string">
			<minLength value="1"></minLength>
			<maxLength value="60"></maxLength>
		</restriction>
	</simpleType>
	<simpleType name="Portion">
		<restriction base="string">
			<pattern value="50|100|150|1шт.|2шт." />
		</restriction>
	</simpleType>
	<simpleType name="Price">
		<restriction base="integer">
			<minExclusive value="200000"></minExclusive>
			<maxExclusive value="1000000"></maxExclusive>
		</restriction>
	</simpleType>
</schema>

=== FatSharky/Task3/src/source/Menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns="http://www.example.org/MenuSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/MenuSchema MenuSchema.xsd">
	<kind id="id_1">
		<kind-name>Холодные закуски</kind-name>
		<kind-content>
			<dish id="asorti">
				<photo>photo</photo>
				<name>Асорти рыбное</name>
				<description>Слабосоленая форель</description>
				<portion>100</portion>
				<price>500000</price>
			</dish>
			<dish id="zakuski">
				<photo>photo</photo>
				<name>Закуска по русски</name>
				<description>Кусочки атлантичекой сельди с отварным картофелем</description>
				<portion>1шт.</portion>
				<price>540000</price>
			</dish>
			<dish id="zakyski2">
				<photo>photo</photo>
				<name>Брынза</name>
				<description>Рассольный сыр, из овечьего молока</description>
				<portion>150</portion>
				<price>900000</price>
			</dish>
			<dish id="pomidor">
				<photo>photo</photo>
				<name>Сеньор Помидор</name>
				<description>Помидор фаршированный сырным муссом</description>
				<portion>150</portion>
				<price>800000</price>
			</dish>
		</kind-content>
	</kind>

	<kind id="id_2">
		<kind-name>Горячие закуски</kind-name>

		<kind-content>
			<dish id="zulien">
				<photo>photo</photo>
				<name>Жульен</name>
				<description>С курицей либо грибами</description>
				<portion>1шт.</portion>
				<price>740000</price>
			</dish>
			<dish id="meat">
				<photo>photo</photo>
				<name>Ахмат мясной</name>
				<description>Колбаса, ветчина, буженина, сыр запеченый</description>
				<portion>2шт.</portion>
				<price>340000</price>
			</dish>
			<dish id="eskato">

				<photo>photo</photo>
				<name>Эскарго</name>
				<description>Виноградные улитки, фаршированные по бургундски</description>
				<portion>150</portion>
				<price>540000</price>
			</dish>
		</kind-content>

	</kind>

	<kind id="id_3">
		<kind-name>Завтраки</kind-name>
		<kind-content>
			<dish id="glaza">
				<photo>photo</photo>
				<name>Глазунья</name>
				<description>2-а яйца</description>
				<portion>1шт.</portion>
				<price>220000</price>
			</dish>
			<dish id="omlet">
	<photo>photo</photo>
	<name>Омлет</name>
	<description>Яйца,молоко,мука</description>
				<portion>2шт.</portion>
				<price>390000</price>
			</dish>
		</kind-content>

	</kind>

</menu>
